name: "개발 (Dev)"
description: "구현 작업"
labels: ["team:dev"]
body:
  - type: textarea
    id: what
    attributes:
      label: 구현 내용
      description: "무엇을 만들/수정하나?"
    validations:
      required: true
  - type: textarea
    id: files
    attributes:
      label: 영향 파일/폴더
      description: "예: res://scripts/, res://data/"
  - type: textarea
    id: ac
    attributes:
      label: 완료 기준 (Acceptance Criteria)
    validations:
      required: true
  - type: textarea
    id: tcs
    attributes:
      label: 연결 테스트케이스(TC)
