name: Planner (Design / Balance)
description: Design tasks (rules, balance, economy, UX)
title: "[PLAN] "
labels: ["planner"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What problem are we solving? (1-2 sentences)
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope / Non-scope
      description: Bullet list of what IS and IS NOT included
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: What evidence makes this done? (TC + metric)
    validations:
      required: true
