name: "QA"
description: "재현/테스트/지표 산출"
labels: ["team:qa"]
body:
  - type: textarea
    id: repro
    attributes:
      label: 재현 절차
      description: "Step-by-step"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 기대 결과
      description: "Pass 조건"
    validations:
      required: true
  - type: textarea
    id: data
    attributes:
      label: 로그/측정
      description: "어떤 로그/지표를 남기나?"
